[versions]
agp = "8.8.0"
androidSdk = "11.5.0"
androidSdkGeojson = "5.9.0"
blurry = "4.0.1"
glide = "5.0.5"
graphhopperCore = "6.2"
kotlin = "1.9.24"
coreKtx = "1.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
library = "2.2.8"
material = "1.13.0"
media3Exoplayer = "1.8.0"
okhttpBom = "4.11.0"
playServicesLocationVersion = "21.0.1"
realmGradlePlugin = "10.18.0"
realmMonarchy = "0.7.1"
recyclerview = "1.4.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.9.3"
lifecycleViewmodelKtx = "2.9.3"
navigationFragmentKtx = "2.8.9"
navigationUiKtx = "2.8.9"
mvrx = "3.0.9"
javax-inject = "1"
flowbinding = "1.2.0"
hilt = "2.52"
dagger = "2.52"
activity = "1.10.1"
moshi = "1.15.0"
retrofit = "2.11.0"
epoxy = "5.0.0"
ktlint = "11.6.0"
preferenceKtx = "1.2.1"
rtspServer = "1.3.2"
camerax = "1.4.2"
uiToolingPreviewAndroid = "1.9.4"
material3Android = "1.4.0"

[libraries]
android-map-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "androidSdk" }
android-sdk-geojson = { module = "org.maplibre.gl:android-sdk-geojson", version.ref = "androidSdkGeojson" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-rtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
blurry = { module = "jp.wasabeef:blurry", version.ref = "blurry" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gms-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
graphhopper-core = { module = "com.graphhopper:graphhopper-core", version.ref = "graphhopperCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
library = { module = "com.github.pedroSG94.RootEncoder:library", version.ref = "library" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mavericks = { group = "com.airbnb.android", name = "mavericks", version.ref = "mvrx" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
flowbinding-android = { module = "io.github.reactivecircus.flowbinding:flowbinding-android", version.ref = "flowbinding" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realmGradlePlugin" }
realm-monarchy = { module = "com.github.Zhuinden:realm-monarchy", version.ref = "realmMonarchy" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kt = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
epoxy = { module = "com.airbnb.android:epoxy", version.ref = "epoxy" }
epoxy-glide = { module = "com.airbnb.android:epoxy-glide-preloading", version.ref = "epoxy" }
epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxy" }
epoxy-paging = { module = "com.airbnb.android:epoxy-paging", version.ref = "epoxy" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
rtsp-server = { module = "com.github.pedroSG94:RTSP-Server", version.ref = "rtspServer" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "kotlin-kapt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
realm-android = { id = "realm-android"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kotlin-parcelize = { id = "kotlin-parcelize"}



